[tox]
no_package = True
env_list = fmt, lint, static, unit

[vars]
src_path = {tox_root}/src
tests_path = {tox_root}/tests

[testenv:fmt]
description = Apply code formatters
deps =
    black
    ruff
commands =
    black {[vars]src_path} {[vars]tests_path}
    ruff check --fix {[vars]src_path} {[vars]tests_path}

[testenv:lint]
description = Check code style and spelling
deps =
    black
    ruff
    codespell
commands =
    black --check {[vars]src_path} {[vars]tests_path}
    ruff check {[vars]src_path} {[vars]tests_path}
    codespell {[vars]src_path} {[vars]tests_path}

[testenv:static]
description = Run static type analysis
deps =
    mypy
    ops>=3.7.0,<4.0
    paas-charm
commands =
    mypy {[vars]src_path}

[testenv:unit]
description = Run charm unit tests
deps =
    pytest
    coverage[toml]
    ops[testing]<4.0
    paas-charm
setenv =
    PYTHONPATH = {tox_root}/lib:{tox_root}/src
commands =
    coverage run --source={[vars]src_path} -m pytest {[vars]tests_path}/unit -v {posargs}
    coverage report --fail-under=90
