name: Documentation checks

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  docs:
    uses: canonical/operator-workflows/.github/workflows/docs_rtd.yaml@main
